# FROM amazoncorretto:17-alpine3.17-jdk
# WORKDIR /app
# RUN apk add maven
# COPY . .
# CMD mvn spring-boot:run
# EXPOSE 8080
FROM amazoncorretto:17-alpine3.17-jdk
WORKDIR /app
RUN apk add maven
EXPOSE 8080